/* eslint-disable comma-dangle */
/* eslint-disable quote-props */
/* eslint-disable quotes */

const wordData = {
  0: [
    {
      "id": "5e9f5ee35eb9e72bc21af4a0",
      "group": 0,
      "page": 0,
      "word": "alcohol",
      "image": "files/01_0002.jpg",
      "audio": "files/01_0002.mp3",
      "audioMeaning": "files/01_0002_meaning.mp3",
      "audioExample": "files/01_0002_example.mp3",
      "textMeaning": "<i>Alcohol</i> is a type of drink that can make people drunk.",
      "textExample": "A person should not drive a car after he or she has been drinking <b>alcohol</b>.",
      "transcription": "[ǽlkəhɔ̀ːl]",
      "textExampleTranslate": "Человек не должен водить машину после того, как он выпил алкоголь",
      "textMeaningTranslate": "Алкоголь - это тип напитка, который может сделать людей пьяными",
      "wordTranslate": "алкоголь",
      "wordsPerExampleSentence": 15
    },
    {
      "id": "5e9f5ee35eb9e72bc21af4a2",
      "group": 0,
      "page": 0,
      "word": "boat",
      "image": "files/01_0005.jpg",
      "audio": "files/01_0005.mp3",
      "audioMeaning": "files/01_0005_meaning.mp3",
      "audioExample": "files/01_0005_example.mp3",
      "textMeaning": "A <i>boat</i> is a vehicle that moves across water.",
      "textExample": "There is a small <b>boat</b> on the lake.",
      "transcription": "[bout]",
      "textExampleTranslate": "На озере есть маленькая лодка",
      "textMeaningTranslate": "Лодка - это транспортное средство, которое движется по воде",
      "wordTranslate": "лодка",
      "wordsPerExampleSentence": 8
    },
    {
      "id": "5e9f5ee35eb9e72bc21af4a1",
      "group": 0,
      "page": 0,
      "word": "agree",
      "image": "files/01_0001.jpg",
      "audio": "files/01_0001.mp3",
      "audioMeaning": "files/01_0001_meaning.mp3",
      "audioExample": "files/01_0001_example.mp3",
      "textMeaning": "To <i>agree</i> is to have the same opinion or belief as another person.",
      "textExample": "The students <b>agree</b> they have too much homework.",
      "transcription": "[əgríː]",
      "textExampleTranslate": "Студенты согласны, что у них слишком много домашней работы",
      "textMeaningTranslate": "Согласиться - значит иметь то же мнение или убеждение, что и другой человек",
      "wordTranslate": "согласна",
      "wordsPerExampleSentence": 8
    },
    {
      "id": "5e9f5ee35eb9e72bc21af4a3",
      "group": 0,
      "page": 0,
      "word": "arrive",
      "image": "files/01_0003.jpg",
      "audio": "files/01_0003.mp3",
      "audioMeaning": "files/01_0003_meaning.mp3",
      "audioExample": "files/01_0003_example.mp3",
      "textMeaning": "To <i>arrive</i> is to get somewhere.",
      "textExample": "They <b>arrived</b> at school at 7 a.m.",
      "transcription": "[əráiv]",
      "textExampleTranslate": "Они прибыли в школу в 7 часов утра",
      "textMeaningTranslate": "Приехать значит попасть куда-то",
      "wordTranslate": "прибыть",
      "wordsPerExampleSentence": 7
    },
    {
      "id": "5e9f5ee35eb9e72bc21af4a4",
      "group": 0,
      "page": 0,
      "word": "August",
      "image": "files/01_0004.jpg",
      "audio": "files/01_0004.mp3",
      "audioMeaning": "files/01_0004_meaning.mp3",
      "audioExample": "files/01_0004_example.mp3",
      "textMeaning": "<i>August</i> is the eighth month of the year.",
      "textExample": "Is your birthday in <b>August</b>?",
      "transcription": "[ɔ́ːgəst]",
      "textExampleTranslate": "У тебя день рождения в августе?",
      "textMeaningTranslate": "Август - восьмой месяц года",
      "wordTranslate": "август",
      "wordsPerExampleSentence": 5
    },
    {
      "id": "5e9f5ee35eb9e72bc21af4a5",
      "group": 0,
      "page": 0,
      "word": "breakfast",
      "image": "files/01_0006.jpg",
      "audio": "files/01_0006.mp3",
      "audioMeaning": "files/01_0006_meaning.mp3",
      "audioExample": "files/01_0006_example.mp3",
      "textMeaning": "<i>Breakfast</i> is the morning meal.",
      "textExample": "I ate eggs for <b>breakfast</b>.",
      "transcription": "[brekfəst]",
      "textExampleTranslate": "Я ел яйца на завтрак",
      "textMeaningTranslate": "Завтрак - это утренняя трапеза",
      "wordTranslate": "завтрак",
      "wordsPerExampleSentence": 5
    },
    {
      "id": "5e9f5ee35eb9e72bc21af4a6",
      "group": 0,
      "page": 0,
      "word": "camera",
      "image": "files/01_0007.jpg",
      "audio": "files/01_0007.mp3",
      "audioMeaning": "files/01_0007_meaning.mp3",
      "audioExample": "files/01_0007_example.mp3",
      "textMeaning": "A <i>camera</i> is a piece of equipment that takes pictures.",
      "textExample": "I brought my <b>camera</b> on my vacation.",
      "transcription": "[kǽmərə]",
      "textExampleTranslate": "Я принес свою камеру в отпуск",
      "textMeaningTranslate": "Камера - это часть оборудования, которая делает снимки",
      "wordTranslate": "камера",
      "wordsPerExampleSentence": 7
    },
    {
      "id": "5e9f5ee35eb9e72bc21af4a7",
      "group": 0,
      "page": 0,
      "word": "capital",
      "image": "files/01_0008.jpg",
      "audio": "files/01_0008.mp3",
      "audioMeaning": "files/01_0008_meaning.mp3",
      "audioExample": "files/01_0008_example.mp3",
      "textMeaning": "A <i>capital</i> is a city where a country’s government is based.",
      "textExample": "The <b>capital</b> of the United States is Washington, D.C.",
      "transcription": "[kæpətl]",
      "textExampleTranslate": "Столица Соединенных Штатов - Вашингтон, округ Колумбия",
      "textMeaningTranslate": "Столица - это город, в котором базируется правительство страны",
      "wordTranslate": "столица",
      "wordsPerExampleSentence": 9
    },
    {
      "id": "5e9f5ee35eb9e72bc21af4a8",
      "group": 0,
      "page": 0,
      "word": "catch",
      "image": "files/01_0009.jpg",
      "audio": "files/01_0009.mp3",
      "audioMeaning": "files/01_0009_meaning.mp3",
      "audioExample": "files/01_0009_example.mp3",
      "textMeaning": "To <i>catch</i> is to grab or get something.",
      "textExample": "Did you <b>catch</b> the ball during the baseball game?",
      "transcription": "[kætʃ]",
      "textExampleTranslate": "Вы поймали мяч во время игры в бейсбол?",
      "textMeaningTranslate": "Поймать - значит схватить или получить что-то",
      "wordTranslate": "поймать",
      "wordsPerExampleSentence": 9
    },
    {
      "id": "5e9f5ee35eb9e72bc21af4a9",
      "group": 0,
      "page": 0,
      "word": "duck",
      "image": "files/01_0010.jpg",
      "audio": "files/01_0010.mp3",
      "audioMeaning": "files/01_0010_meaning.mp3",
      "audioExample": "files/01_0010_example.mp3",
      "textMeaning": "A <i>duck</i> is a small water bird.",
      "textExample": "People feed <b>ducks</b> at the lake.",
      "transcription": "[dʌk]",
      "textExampleTranslate": "Люди кормят уток у озера",
      "textMeaningTranslate": "Утка - маленькая водяная птица",
      "wordTranslate": "утка",
      "wordsPerExampleSentence": 6
    },
    {
      "id": "5e9f5ee35eb9e72bc21af4aa",
      "group": 0,
      "page": 0,
      "word": "enjoy",
      "image": "files/01_0011.jpg",
      "audio": "files/01_0011.mp3",
      "audioMeaning": "files/01_0011_meaning.mp3",
      "audioExample": "files/01_0011_example.mp3",
      "textMeaning": "To <i>enjoy</i> is to like something.",
      "textExample": "The woman <b>enjoys</b> riding her bicycle.",
      "transcription": "[indʒɔ́i]",
      "textExampleTranslate": "Женщина любит кататься на велосипеде",
      "textMeaningTranslate": "Наслаждаться значит любить что-то",
      "wordTranslate": "наслаждаться",
      "wordsPerExampleSentence": 6
    },
    {
      "id": "5e9f5ee35eb9e72bc21af4ab",
      "group": 0,
      "page": 0,
      "word": "invite",
      "image": "files/01_0012.jpg",
      "audio": "files/01_0012.mp3",
      "audioMeaning": "files/01_0012_meaning.mp3",
      "audioExample": "files/01_0012_example.mp3",
      "textMeaning": "To <i>invite</i> is to ask someone to come to a place or event.",
      "textExample": "I will <b>invite</b> my friends to my birthday party.",
      "transcription": "[inváit]",
      "textExampleTranslate": "Я приглашаю своих друзей на мой день рождения",
      "textMeaningTranslate": "Пригласить - это попросить кого-нибудь прийти на место или событие",
      "wordTranslate": "пригласить",
      "wordsPerExampleSentence": 9
    },
    {
      "id": "5e9f5ee35eb9e72bc21af4ac",
      "group": 0,
      "page": 0,
      "word": "month",
      "image": "files/01_0014.jpg",
      "audio": "files/01_0014.mp3",
      "audioMeaning": "files/01_0014_meaning.mp3",
      "audioExample": "files/01_0014_example.mp3",
      "textMeaning": "A <i>month</i> is one of 12 periods of time in one year.",
      "textExample": "January is the first <b>month</b> of the year.",
      "transcription": "[mʌnθ]",
      "textExampleTranslate": "январь - первый месяц года",
      "textMeaningTranslate": "Месяц - это один из 12 периодов времени в году",
      "wordTranslate": "месяц",
      "wordsPerExampleSentence": 8
    },
    {
      "id": "5e9f5ee35eb9e72bc21af4ad",
      "group": 0,
      "page": 0,
      "word": "travel",
      "image": "files/01_0015.jpg",
      "audio": "files/01_0015.mp3",
      "audioMeaning": "files/01_0015_meaning.mp3",
      "audioExample": "files/01_0015_example.mp3",
      "textMeaning": "To <i>travel</i> is to go to a faraway place on vacation or business.",
      "textExample": "They will <b>travel</b> to Argentina this summer.",
      "transcription": "[trǽvəl]",
      "textExampleTranslate": "Этим летом они отправятся в Аргентину",
      "textMeaningTranslate": "Путешествовать - это отправиться в далекое место на отдых или по делам",
      "wordTranslate": "путешествовать",
      "wordsPerExampleSentence": 7
    },
    {
      "id": "5e9f5ee35eb9e72bc21af4ae",
      "group": 0,
      "page": 0,
      "word": "love",
      "image": "files/01_0013.jpg",
      "audio": "files/01_0013.mp3",
      "audioMeaning": "files/01_0013_meaning.mp3",
      "audioExample": "files/01_0013_example.mp3",
      "textMeaning": "To <i>love</i> is to like something or someone a lot.",
      "textExample": "I <b>love</b> my family very much.",
      "transcription": "[lʌv]",
      "textExampleTranslate": "Я очень люблю свою семью",
      "textMeaningTranslate": "Любить значит любить что-то или кого-то много",
      "wordTranslate": "любовь",
      "wordsPerExampleSentence": 6
    },
    {
      "id": "5e9f5ee35eb9e72bc21af4af",
      "group": 0,
      "page": 0,
      "word": "typical",
      "image": "files/01_0016.jpg",
      "audio": "files/01_0016.mp3",
      "audioMeaning": "files/01_0016_meaning.mp3",
      "audioExample": "files/01_0016_example.mp3",
      "textMeaning": "If something is <i>typical</i>, it is normal, or something that usually happens.",
      "textExample": "My <b>typical</b> breakfast is toast and eggs.",
      "transcription": "[típikəl]",
      "textExampleTranslate": "Мой типичный завтрак - тост и яйца",
      "textMeaningTranslate": "Если что-то типичное, это нормально, или что-то, что обычно происходит",
      "wordTranslate": "типичный",
      "wordsPerExampleSentence": 7
    },
    {
      "id": "5e9f5ee35eb9e72bc21af4b0",
      "group": 0,
      "page": 0,
      "word": "visit",
      "image": "files/01_0017.jpg",
      "audio": "files/01_0017.mp3",
      "audioMeaning": "files/01_0017_meaning.mp3",
      "audioExample": "files/01_0017_example.mp3",
      "textMeaning": "To <i>visit</i> is to go and spend time in another place or see another person.",
      "textExample": "She wants to <b>visit</b> her grandmother.",
      "transcription": "[vízit]",
      "textExampleTranslate": "Она хочет навестить свою бабушку",
      "textMeaningTranslate": "Посетить - значит пойти и провести время в другом месте или увидеть другого человека",
      "wordTranslate": "посещение",
      "wordsPerExampleSentence": 6
    },
    {
      "id": "5e9f5ee35eb9e72bc21af4b1",
      "group": 0,
      "page": 0,
      "word": "weather",
      "image": "files/01_0018.jpg",
      "audio": "files/01_0018.mp3",
      "audioMeaning": "files/01_0018_meaning.mp3",
      "audioExample": "files/01_0018_example.mp3",
      "textMeaning": "<i>Weather</i> is the temperature and the state of the outdoors.",
      "textExample": "Today’s <b>weather</b> is rainy and cloudy.",
      "transcription": "[weðər]",
      "textExampleTranslate": "Сегодня погода дождливая и облачная",
      "textMeaningTranslate": "Погода это температура и состояние на улице",
      "wordTranslate": "погода",
      "wordsPerExampleSentence": 6
    },
    {
      "id": "5e9f5ee35eb9e72bc21af4b2",
      "group": 0,
      "page": 0,
      "word": "wine",
      "image": "files/01_0020.jpg",
      "audio": "files/01_0020.mp3",
      "audioMeaning": "files/01_0020_meaning.mp3",
      "audioExample": "files/01_0020_example.mp3",
      "textMeaning": "<i>Wine</i> is an alcoholic drink made from grapes.",
      "textExample": "The store carried both red and white <b>wine</b>.",
      "transcription": "[wain]",
      "textExampleTranslate": "В магазине было красное и белое вино",
      "textMeaningTranslate": "Вино - это алкогольный напиток из винограда",
      "wordTranslate": "вино",
      "wordsPerExampleSentence": 8
    },
    {
      "id": "5e9f5ee35eb9e72bc21af4b3",
      "group": 0,
      "page": 0,
      "word": "week",
      "image": "files/01_0019.jpg",
      "audio": "files/01_0019.mp3",
      "audioMeaning": "files/01_0019_meaning.mp3",
      "audioExample": "files/01_0019_example.mp3",
      "textMeaning": "A <i>week</i> is a period of time that is seven days long.",
      "textExample": "What are you doing next <b>week</b>?",
      "transcription": "[wiːk]",
      "textExampleTranslate": "Что ты делаешь на следующей неделе?",
      "textMeaningTranslate": "Неделя - это период времени, который длится семь дней",
      "wordTranslate": "неделя",
      "wordsPerExampleSentence": 6
    }
  ],
  1: [
    {
      "id": "5e9f5ee35eb9e72bc21af6f8",
      "group": 1,
      "page": 0,
      "word": "because",
      "image": "files/01_0601.jpg",
      "audio": "files/01_0601.mp3",
      "audioMeaning": "files/01_0601_meaning.mp3",
      "audioExample": "files/01_0601_example.mp3",
      "textMeaning": "<i>Because</i> introduces a reason for something.",
      "textExample": "We need to study <b>because</b> we have a test tomorrow.",
      "transcription": "[bikɔ́ːz]",
      "textExampleTranslate": "Нам нужно учиться, потому что завтра у нас тест",
      "textMeaningTranslate": "Потому что вводит причину чего-то",
      "wordTranslate": "потому что",
      "wordsPerExampleSentence": 10
    },
    {
      "id": "5e9f5ee35eb9e72bc21af6fb",
      "group": 1,
      "page": 0,
      "word": "flower",
      "image": "files/01_0604.jpg",
      "audio": "files/01_0604.mp3",
      "audioMeaning": "files/01_0604_meaning.mp3",
      "audioExample": "files/01_0604_example.mp3",
      "textMeaning": "A <i>flower</i> is the colored part of a plant.",
      "textExample": "She gave pink <b>flowers</b> to her grandmother.",
      "transcription": "[fáuər]",
      "textExampleTranslate": "Она дала розовые цветы своей бабушке",
      "textMeaningTranslate": "Цветок - это цветная часть растения",
      "wordTranslate": "цветок",
      "wordsPerExampleSentence": 7
    },
    {
      "id": "5e9f5ee35eb9e72bc21af6fa",
      "group": 1,
      "page": 0,
      "word": "expensive",
      "image": "files/01_0603.jpg",
      "audio": "files/01_0603.mp3",
      "audioMeaning": "files/01_0603_meaning.mp3",
      "audioExample": "files/01_0603_example.mp3",
      "textMeaning": "<i>Expensive</i> things cost a lot of money.",
      "textExample": "My friend drives an <b>expensive</b> sports car.",
      "transcription": "[ikspénsiv]",
      "textExampleTranslate": "Мой друг водит дорогой спортивный автомобиль",
      "textMeaningTranslate": "Дорогие вещи стоят больших денег",
      "wordTranslate": "дорогой",
      "wordsPerExampleSentence": 7
    },
    {
      "id": "5e9f5ee35eb9e72bc21af6f9",
      "group": 1,
      "page": 0,
      "word": "east",
      "image": "files/01_0602.jpg",
      "audio": "files/01_0602.mp3",
      "audioMeaning": "files/01_0602_meaning.mp3",
      "audioExample": "files/01_0602_example.mp3",
      "textMeaning": "<i>East</i> is the direction the sun rises from.",
      "textExample": "My window looks to the <b>east</b>, so I can watch the sunrise every morning.",
      "transcription": "[iːst]",
      "textExampleTranslate": "Мое окно смотрит на восток, поэтому я могу наблюдать восход солнца каждое утро",
      "textMeaningTranslate": "Восток - это направление, из которого восходит солнце",
      "wordTranslate": "восток",
      "wordsPerExampleSentence": 14
    },
    {
      "id": "5e9f5ee35eb9e72bc21af6fc",
      "group": 1,
      "page": 0,
      "word": "garden",
      "image": "files/01_0605.jpg",
      "audio": "files/01_0605.mp3",
      "audioMeaning": "files/01_0605_meaning.mp3",
      "audioExample": "files/01_0605_example.mp3",
      "textMeaning": "A <i>garden</i> is an area where people grow plants.",
      "textExample": "The <b>garden</b> is very bright and colorful in the spring.",
      "transcription": "[gάːrdn]",
      "textExampleTranslate": "Сад очень яркий и красочный весной",
      "textMeaningTranslate": "Сад - это место, где люди выращивают растения",
      "wordTranslate": "сад",
      "wordsPerExampleSentence": 10
    },
    {
      "id": "5e9f5ee35eb9e72bc21af6fd",
      "group": 1,
      "page": 0,
      "word": "holiday",
      "image": "files/01_0606.jpg",
      "audio": "files/01_0606.mp3",
      "audioMeaning": "files/01_0606_meaning.mp3",
      "audioExample": "files/01_0606_example.mp3",
      "textMeaning": "A <i>holiday</i> is a special day of celebration.",
      "textExample": "Monday was a <b>holiday</b>, so there was no school or work.",
      "transcription": "[hάlədèi]",
      "textExampleTranslate": "Понедельник был выходным, поэтому не было школы или работы",
      "textMeaningTranslate": "Праздник - особый день празднования",
      "wordTranslate": "праздничный день",
      "wordsPerExampleSentence": 11
    },
    {
      "id": "5e9f5ee35eb9e72bc21af6fe",
      "group": 1,
      "page": 0,
      "word": "many",
      "image": "files/01_0607.jpg",
      "audio": "files/01_0607.mp3",
      "audioMeaning": "files/01_0607_meaning.mp3",
      "audioExample": "files/01_0607_example.mp3",
      "textMeaning": "<i>Many</i> shows that there is a large number of something.",
      "textExample": "There are <b>many</b> people on the street.",
      "transcription": "[méni]",
      "textExampleTranslate": "На улице много людей",
      "textMeaningTranslate": "Многие показывают, что есть много чего-то",
      "wordTranslate": "многие",
      "wordsPerExampleSentence": 7
    },
    {
      "id": "5e9f5ee35eb9e72bc21af700",
      "group": 1,
      "page": 0,
      "word": "mountain",
      "image": "files/01_0609.jpg",
      "audio": "files/01_0609.mp3",
      "audioMeaning": "files/01_0609_meaning.mp3",
      "audioExample": "files/01_0609_example.mp3",
      "textMeaning": "A <i>mountain</i> is a very high hill.",
      "textExample": "Mount Everest is the highest <b>mountain</b> in the world.",
      "transcription": "[máuntən]",
      "textExampleTranslate": "Гора Эверест - самая высокая гора в мире",
      "textMeaningTranslate": "Гора - это очень высокий холм",
      "wordTranslate": "гора",
      "wordsPerExampleSentence": 9
    },
    {
      "id": "5e9f5ee35eb9e72bc21af6ff",
      "group": 1,
      "page": 0,
      "word": "million",
      "image": "files/01_0608.jpg",
      "audio": "files/01_0608.mp3",
      "audioMeaning": "files/01_0608_meaning.mp3",
      "audioExample": "files/01_0608_example.mp3",
      "textMeaning": "A <i>million</i> is another way to write the number 1,000,000.",
      "textExample": "Almost 19 <b>million</b> people live in Delhi, India.",
      "transcription": "[míljən]",
      "textExampleTranslate": "Почти 19 миллионов человек живут в Дели, Индия",
      "textMeaningTranslate": "Миллион - это еще один способ написать число 1 000 000",
      "wordTranslate": "миллион",
      "wordsPerExampleSentence": 8
    },
    {
      "id": "5e9f5ee35eb9e72bc21af702",
      "group": 1,
      "page": 0,
      "word": "popular",
      "image": "files/01_0611.jpg",
      "audio": "files/01_0611.mp3",
      "audioMeaning": "files/01_0611_meaning.mp3",
      "audioExample": "files/01_0611_example.mp3",
      "textMeaning": "A <i>popular</i> thing is liked by many people.",
      "textExample": "These people are listening to a <b>popular</b> man speak.",
      "transcription": "[pάpjulər]",
      "textExampleTranslate": "Эти люди слушают разговор популярного человека",
      "textMeaningTranslate": "Популярная вещь нравится многим людям",
      "wordTranslate": "популярный",
      "wordsPerExampleSentence": 9
    },
    {
      "id": "5e9f5ee35eb9e72bc21af701",
      "group": 1,
      "page": 0,
      "word": "place",
      "image": "files/01_0610.jpg",
      "audio": "files/01_0610.mp3",
      "audioMeaning": "files/01_0610_meaning.mp3",
      "audioExample": "files/01_0610_example.mp3",
      "textMeaning": "A <i>place</i> is a space or area.",
      "textExample": "A library is a <b>place</b> where people can read books.",
      "transcription": "[pleis]",
      "textExampleTranslate": "Библиотека - это место, где люди могут читать книги",
      "textMeaningTranslate": "Место - это пространство или область",
      "wordTranslate": "место",
      "wordsPerExampleSentence": 10
    },
    {
      "id": "5e9f5ee35eb9e72bc21af703",
      "group": 1,
      "page": 0,
      "word": "ski",
      "image": "files/01_0612.jpg",
      "audio": "files/01_0612.mp3",
      "audioMeaning": "files/01_0612_meaning.mp3",
      "audioExample": "files/01_0612_example.mp3",
      "textMeaning": "To <i>ski</i> is to glide on long pieces of wood or metal over snow.",
      "textExample": "The man likes to <b>ski</b> and goes every weekend.",
      "transcription": "[skiː]",
      "textExampleTranslate": "Мужчина любит кататься на лыжах и ездит каждые выходные",
      "textMeaningTranslate": "Кататься на лыжах - значит скользить по длинным кускам дерева или металла по снегу",
      "wordTranslate": "лыжи",
      "wordsPerExampleSentence": 9
    },
    {
      "id": "5e9f5ee35eb9e72bc21af704",
      "group": 1,
      "page": 0,
      "word": "tower",
      "image": "files/01_0615.jpg",
      "audio": "files/01_0615.mp3",
      "audioMeaning": "files/01_0615_meaning.mp3",
      "audioExample": "files/01_0615_example.mp3",
      "textMeaning": "A <i>tower</i> is a tall, narrow building.",
      "textExample": "This is a very famous <b>tower</b> in Italy.",
      "transcription": "[táuər]",
      "textExampleTranslate": "Это очень известная башня в Италии",
      "textMeaningTranslate": "Башня - это высокое узкое здание",
      "wordTranslate": "башня",
      "wordsPerExampleSentence": 8
    },
    {
      "id": "5e9f5ee35eb9e72bc21af705",
      "group": 1,
      "page": 0,
      "word": "such",
      "image": "files/01_0613.jpg",
      "audio": "files/01_0613.mp3",
      "audioMeaning": "files/01_0613_meaning.mp3",
      "audioExample": "files/01_0613_example.mp3",
      "textMeaning": "<i>Such</i> means “like this”.",
      "textExample": "I have never seen <b>such</b> a beautiful sunset before.",
      "transcription": "[sʌtʃ]",
      "textExampleTranslate": "Я никогда раньше не видел такой красивый закат",
      "textMeaningTranslate": "Такие означает 'как это'",
      "wordTranslate": "такой",
      "wordsPerExampleSentence": 9
    },
    {
      "id": "5e9f5ee35eb9e72bc21af706",
      "group": 1,
      "page": 0,
      "word": "total",
      "image": "files/01_0614.jpg",
      "audio": "files/01_0614.mp3",
      "audioMeaning": "files/01_0614_meaning.mp3",
      "audioExample": "files/01_0614_example.mp3",
      "textMeaning": "<i>Total</i> shows that everyone or everything has been counted.",
      "textExample": ".The <b>total</b> cost of the items she bought was $52.",
      "transcription": "[tóutl]",
      "textExampleTranslate": "Общая стоимость предметов, которые она купила, составила 52 доллара",
      "textMeaningTranslate": "Всего показывает, что все или все было посчитано",
      "wordTranslate": "всего",
      "wordsPerExampleSentence": 10
    },
    {
      "id": "5e9f5ee35eb9e72bc21af707",
      "group": 1,
      "page": 0,
      "word": "town",
      "image": "files/01_0616.jpg",
      "audio": "files/01_0616.mp3",
      "audioMeaning": "files/01_0616_meaning.mp3",
      "audioExample": "files/01_0616_example.mp3",
      "textMeaning": "A <i>town</i> is a place where people live and work, and is smaller than a city.",
      "textExample": "I come from a small <b>town</b>, and everyone there knows each other.",
      "transcription": "[taun]",
      "textExampleTranslate": "Я из маленького городка, и все там знают друг друга",
      "textMeaningTranslate": "Город - это место, где люди живут и работают, и он меньше города",
      "wordTranslate": "город",
      "wordsPerExampleSentence": 12
    },
    {
      "id": "5e9f5ee35eb9e72bc21af708",
      "group": 1,
      "page": 0,
      "word": "train",
      "image": "files/01_0617.jpg",
      "audio": "files/01_0617.mp3",
      "audioMeaning": "files/01_0617_meaning.mp3",
      "audioExample": "files/01_0617_example.mp3",
      "textMeaning": "A <i>train</i> is a group of railway cars connected together.",
      "textExample": "The <b>train</b> is very fast, so we can get home in one hour.",
      "transcription": "[trein]",
      "textExampleTranslate": "Поезд очень быстрый, поэтому мы можем добраться домой за один час",
      "textMeaningTranslate": "Поезд - это группа железнодорожных вагонов, соединенных вместе",
      "wordTranslate": "поезд",
      "wordsPerExampleSentence": 13
    },
    {
      "id": "5e9f5ee35eb9e72bc21af709",
      "group": 1,
      "page": 0,
      "word": "walk",
      "image": "files/01_0618.jpg",
      "audio": "files/01_0618.mp3",
      "audioMeaning": "files/01_0618_meaning.mp3",
      "audioExample": "files/01_0618_example.mp3",
      "textMeaning": "To <i>walk</i> is to move forward using legs, but it is slower than running.",
      "textExample": "The children <b>walk</b> to school in the morning.",
      "transcription": "[wɔːk]",
      "textExampleTranslate": "Дети гуляют в школу по утрам",
      "textMeaningTranslate": "Ходить - значит двигаться вперед, используя ноги, но это медленнее, чем бег",
      "wordTranslate": "ходить",
      "wordsPerExampleSentence": 8
    },
    {
      "id": "5e9f5ee35eb9e72bc21af70a",
      "group": 1,
      "page": 0,
      "word": "world",
      "image": "files/01_0620.jpg",
      "audio": "files/01_0620.mp3",
      "audioMeaning": "files/01_0620_meaning.mp3",
      "audioExample": "files/01_0620_example.mp3",
      "textMeaning": "The <i>world</i> is the Earth and all the people and things in it.",
      "textExample": "What are the names of the five oceans of the <b>world</b>?",
      "transcription": "[wəːrld]",
      "textExampleTranslate": "Как называются пять океанов мира?",
      "textMeaningTranslate": "Мир - это Земля и все люди и вещи в ней",
      "wordTranslate": "мир",
      "wordsPerExampleSentence": 11
    },
    {
      "id": "5e9f5ee35eb9e72bc21af70b",
      "group": 1,
      "page": 0,
      "word": "watch",
      "image": "files/01_0619.jpg",
      "audio": "files/01_0619.mp3",
      "audioMeaning": "files/01_0619_meaning.mp3",
      "audioExample": "files/01_0619_example.mp3",
      "textMeaning": "To <i>watch</i> is to look at someone or something for a period of time.",
      "textExample": "My friend came over to <b>watch</b> a movie with me.",
      "transcription": "[waʧ]",
      "textExampleTranslate": "Мой друг пришел посмотреть фильм со мной",
      "textMeaningTranslate": "Смотреть - значит смотреть на кого-то или что-то в течение определенного периода времени",
      "wordTranslate": "смотреть",
      "wordsPerExampleSentence": 10
    }
  ],
  2: [
    {
      "id": "5e9f5ee35eb9e72bc21afba9",
      "group": 3,
      "page": 0,
      "word": "accountable",
      "image": "files/01_1801.jpg",
      "audio": "files/01_1801.mp3",
      "audioMeaning": "files/01_1801_meaning.mp3",
      "audioExample": "files/01_1801_example.mp3",
      "textMeaning": "When someone is <i>accountable</i>, he or she is responsible for the effects of his or her actions.",
      "textExample": "Political leaders are <b>accountable</b> to the people they represent.",
      "transcription": "[əkáuntəbl]",
      "textExampleTranslate": "Политические лидеры ответственны перед людьми, которых они представляют",
      "textMeaningTranslate": "Когда кто-то несет ответственность, он или она несут ответственность за последствия своих действий",
      "wordTranslate": "подотчетны",
      "wordsPerExampleSentence": 9
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbab",
      "group": 3,
      "page": 0,
      "word": "coin",
      "image": "files/01_1804.jpg",
      "audio": "files/01_1804.mp3",
      "audioMeaning": "files/01_1804_meaning.mp3",
      "audioExample": "files/01_1804_example.mp3",
      "textMeaning": "To <i>coin</i> is to create a new word or phrase that other people begin to use.",
      "textExample": "The coach <b>coined</b> the phrase, “There is no ‘I’ in team.”",
      "transcription": "[kɔin]",
      "textExampleTranslate": "Тренер придумал фразу 'В команде нет 'я''",
      "textMeaningTranslate": "Монета означает создание нового слова или фразы, которые начинают использовать другие люди",
      "wordTranslate": "монета",
      "wordsPerExampleSentence": 11
    },
    {
      "id": "5e9f5ee35eb9e72bc21afba8",
      "group": 3,
      "page": 0,
      "word": "addictive",
      "image": "files/01_1802.jpg",
      "audio": "files/01_1802.mp3",
      "audioMeaning": "files/01_1802_meaning.mp3",
      "audioExample": "files/01_1802_example.mp3",
      "textMeaning": "If something is <i>addictive</i>, it is hard to stop doing.",
      "textExample": "I think this game is very <b>addictive</b>.",
      "transcription": "[ədíktiv]",
      "textExampleTranslate": "Я думаю, что эта игра очень затягивает",
      "textMeaningTranslate": "Если что-то вызывает привыкание, трудно перестать делать",
      "wordTranslate": "привыкание",
      "wordsPerExampleSentence": 7
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbaa",
      "group": 3,
      "page": 0,
      "word": "agenda",
      "image": "files/01_1803.jpg",
      "audio": "files/01_1803.mp3",
      "audioMeaning": "files/01_1803_meaning.mp3",
      "audioExample": "files/01_1803_example.mp3",
      "textMeaning": "An <i>agenda</i> is a plan or goal that guides someone’s behavior.",
      "textExample": "The man is pushing his questionable <b>agenda</b> on his colleagues.",
      "transcription": "[ədʒéndə]",
      "textExampleTranslate": "Человек выдвигает свою сомнительную повестку дня на своих коллег",
      "textMeaningTranslate": "Повестка дня - это план или цель, определяющая поведение человека",
      "wordTranslate": "повестка дня",
      "wordsPerExampleSentence": 10
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbad",
      "group": 3,
      "page": 0,
      "word": "depression",
      "image": "files/01_1806.jpg",
      "audio": "files/01_1806.mp3",
      "audioMeaning": "files/01_1806_meaning.mp3",
      "audioExample": "files/01_1806_example.mp3",
      "textMeaning": "<i>Depression</i> is a medical condition that makes a person very unhappy for long periods of time.",
      "textExample": "Ron decided to get help for his <b>depression</b>.",
      "transcription": "[dipréʃən]",
      "textExampleTranslate": "Рон решил получить помощь от депрессии",
      "textMeaningTranslate": "Депрессия - это заболевание, которое делает человека очень несчастным в течение длительного времени",
      "wordTranslate": "депрессия",
      "wordsPerExampleSentence": 8
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbac",
      "group": 3,
      "page": 0,
      "word": "correlate",
      "image": "files/01_1805.jpg",
      "audio": "files/01_1805.mp3",
      "audioMeaning": "files/01_1805_meaning.mp3",
      "audioExample": "files/01_1805_example.mp3",
      "textMeaning": "To <i>correlate</i> is to have a close connection to something.",
      "textExample": "Scientists believe that brain size might <b>correlate</b> with intelligence.",
      "transcription": "[kɔ́ːrəlèit]",
      "textExampleTranslate": "Ученые считают, что размер мозга может коррелировать с интеллектом",
      "textMeaningTranslate": "Соотносить это значит иметь тесную связь с чем-то",
      "wordTranslate": "коррелят",
      "wordsPerExampleSentence": 9
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbae",
      "group": 3,
      "page": 0,
      "word": "digital",
      "image": "files/01_1807.jpg",
      "audio": "files/01_1807.mp3",
      "audioMeaning": "files/01_1807_meaning.mp3",
      "audioExample": "files/01_1807_example.mp3",
      "textMeaning": "When something is <i>digital</i>, it is characterized by computer technology.",
      "textExample": "Students prefer to take notes on their laptops and other <b>digital</b> devices.",
      "transcription": "[dídʒətl]",
      "textExampleTranslate": "Студенты предпочитают делать заметки на своих ноутбуках и других цифровых устройствах",
      "textMeaningTranslate": "Когда что-то является цифровым, оно характеризуется компьютерными технологиями",
      "wordTranslate": "цифровой",
      "wordsPerExampleSentence": 12
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbaf",
      "group": 3,
      "page": 0,
      "word": "keyboard",
      "image": "files/01_1809.jpg",
      "audio": "files/01_1809.mp3",
      "audioMeaning": "files/01_1809_meaning.mp3",
      "audioExample": "files/01_1809_example.mp3",
      "textMeaning": "A <i>keyboard</i> has buttons marked with letters and numbers that are pressed to put information into a computer.",
      "textExample": "Paul spilled coffee all over his <b>keyboard</b>.",
      "transcription": "[kíbɔːrd]",
      "textExampleTranslate": "Пол разлил кофе по всей клавиатуре",
      "textMeaningTranslate": "На клавиатуре есть кнопки, помеченные буквами и цифрами, которые нажимаются для ввода информации в компьютер",
      "wordTranslate": "клавиатура",
      "wordsPerExampleSentence": 7
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb0",
      "group": 3,
      "page": 0,
      "word": "importance",
      "image": "files/01_1808.jpg",
      "audio": "files/01_1808.mp3",
      "audioMeaning": "files/01_1808_meaning.mp3",
      "audioExample": "files/01_1808_example.mp3",
      "textMeaning": "<i>Importance</i> is the quality or state of being important, valuable, or significant.",
      "textExample": "The professor lectured the students on the <b>importance</b> of communication strategies.",
      "transcription": "[impɔ́ːrtəns]",
      "textExampleTranslate": "Профессор читал лекции студентам о важности коммуникационных стратегий",
      "textMeaningTranslate": "Важность - это качество или состояние важности, ценности или значимости",
      "wordTranslate": "значение",
      "wordsPerExampleSentence": 11
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb2",
      "group": 3,
      "page": 0,
      "word": "media",
      "image": "files/01_1811.jpg",
      "audio": "files/01_1811.mp3",
      "audioMeaning": "files/01_1811_meaning.mp3",
      "audioExample": "files/01_1811_example.mp3",
      "textMeaning": "<i>Media</i> is the different ways of entertaining and giving information to the public.",
      "textExample": "Many people like to express their opinions online using social <b>media</b>.",
      "transcription": "[míːdiə]",
      "textExampleTranslate": "Многие люди хотели бы выразить свое мнение в Интернете с помощью социальных сетей",
      "textMeaningTranslate": "СМИ - это разные способы развлечения и предоставления информации общественности",
      "wordTranslate": "CМИ",
      "wordsPerExampleSentence": 11
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb1",
      "group": 3,
      "page": 0,
      "word": "loneliness",
      "image": "files/01_1810.jpg",
      "audio": "files/01_1810.mp3",
      "audioMeaning": "files/01_1810_meaning.mp3",
      "audioExample": "files/01_1810_example.mp3",
      "textMeaning": "<i>Loneliness</i> is the unhappiness that is felt by someone if they do not have any friends.",
      "textExample": "Many people join social clubs to escape <b>loneliness</b>.",
      "transcription": "[lóunlinis]",
      "textExampleTranslate": "Многие люди вступают в социальные клубы, чтобы избежать одиночества",
      "textMeaningTranslate": "Одиночество - это несчастье, которое кто-то чувствует, если у него нет друзей",
      "wordTranslate": "одиночество",
      "wordsPerExampleSentence": 8
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb3",
      "group": 3,
      "page": 0,
      "word": "platform",
      "image": "files/01_1812.jpg",
      "audio": "files/01_1812.mp3",
      "audioMeaning": "files/01_1812_meaning.mp3",
      "audioExample": "files/01_1812_example.mp3",
      "textMeaning": "A <i>platform</i> is something that allows someone to tell a large number of people about an idea, product, etc.",
      "textExample": "The band uses their music as a <b>platform</b> to express their political beliefs.",
      "transcription": "[plǽtfɔːrm]",
      "textExampleTranslate": "Группа использует свою музыку в качестве платформы для выражения своих политических убеждений",
      "textMeaningTranslate": "Платформа - это то, что позволяет кому-то рассказать большому количеству людей об идее, продукте и т. Д",
      "wordTranslate": "платформа",
      "wordsPerExampleSentence": 13
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb4",
      "group": 3,
      "page": 0,
      "word": "presence",
      "image": "files/01_1814.jpg",
      "audio": "files/01_1814.mp3",
      "audioMeaning": "files/01_1814_meaning.mp3",
      "audioExample": "files/01_1814_example.mp3",
      "textMeaning": "<i>Presence</i> is when someone or something is present in a particular place.",
      "textExample": "The researcher discovered the <b>presence</b> of bacteria in the water sample.",
      "transcription": "[prézns]",
      "textExampleTranslate": "Исследователь обнаружил присутствие бактерий в пробе воды",
      "textMeaningTranslate": "Присутствие - это когда кто-то или что-то присутствует в определенном месте",
      "wordTranslate": "присутствие",
      "wordsPerExampleSentence": 11
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb5",
      "group": 3,
      "page": 0,
      "word": "poor",
      "image": "files/01_1813.jpg",
      "audio": "files/01_1813.mp3",
      "audioMeaning": "files/01_1813_meaning.mp3",
      "audioExample": "files/01_1813_example.mp3",
      "textMeaning": "When something is <i>poor</i>, it is not as good as it could or should be.",
      "textExample": "The condition of the sidewalk is very <b>poor</b>.",
      "transcription": "[puər]",
      "textExampleTranslate": "Состояние тротуара очень плохое",
      "textMeaningTranslate": "Когда что-то плохое, это не так хорошо, как могло бы или должно быть",
      "wordTranslate": "бедных",
      "wordsPerExampleSentence": 8
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb7",
      "group": 3,
      "page": 0,
      "word": "surge",
      "image": "files/01_1816.jpg",
      "audio": "files/01_1816.mp3",
      "audioMeaning": "files/01_1816_meaning.mp3",
      "audioExample": "files/01_1816_example.mp3",
      "textMeaning": "A <i>surge</i> is a sudden, large increase in something.",
      "textExample": "All at once, there was a <b>surge</b> of runners at the finish line.",
      "transcription": "[səːrdʒ]",
      "textExampleTranslate": "Внезапно на финише всплеск бегунов",
      "textMeaningTranslate": "Волна - это внезапное, значительное увеличение чего-либо",
      "wordTranslate": "всплеск",
      "wordsPerExampleSentence": 13
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb6",
      "group": 3,
      "page": 0,
      "word": "subject",
      "image": "files/01_1815.jpg",
      "audio": "files/01_1815.mp3",
      "audioMeaning": "files/01_1815_meaning.mp3",
      "audioExample": "files/01_1815_example.mp3",
      "textMeaning": "To <i>subject</i> is to cause or force someone or something to experience something harmful or unpleasant.",
      "textExample": "The location of the trees will <b>subject</b> them to strong winds from the hurricane.",
      "transcription": "[sΛbdʒikt]",
      "textExampleTranslate": "Расположение деревьев подвергнет их сильным ветрам от урагана",
      "textMeaningTranslate": "Субъект должен вызывать или заставлять кого-то или что-либо испытывать что-то вредное или неприятное",
      "wordTranslate": "тема",
      "wordsPerExampleSentence": 14
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbba",
      "group": 3,
      "page": 0,
      "word": "validate",
      "image": "files/01_1820.jpg",
      "audio": "files/01_1820.mp3",
      "audioMeaning": "files/01_1820_meaning.mp3",
      "audioExample": "files/01_1820_example.mp3",
      "textMeaning": "To <i>validate</i> is to make someone feel that his or her ideas and feelings are respected.",
      "textExample": "Winning first prize will <b>validate</b> all of Tony’s hard work.",
      "transcription": "[vǽlədèit]",
      "textExampleTranslate": "Получение первого приза подтвердит всю тяжелую работу Тони",
      "textMeaningTranslate": "Подтвердить - значит заставить кого-то почувствовать, что его или ее идеи и чувства уважают",
      "wordTranslate": "проверка",
      "wordsPerExampleSentence": 10
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb8",
      "group": 3,
      "page": 0,
      "word": "survey",
      "image": "files/01_1817.jpg",
      "audio": "files/01_1817.mp3",
      "audioMeaning": "files/01_1817_meaning.mp3",
      "audioExample": "files/01_1817_example.mp3",
      "textMeaning": "A <i>survey</i> is a set of questions that are asked to a large number of people in order to find out about opinions.",
      "textExample": "I filled out a <b>survey</b> about my shopping experience at the department store.",
      "transcription": "[sərvéi]",
      "textExampleTranslate": "Я заполнил опрос о моем опыте покупок в универмаге",
      "textMeaningTranslate": "Опрос - это набор вопросов, которые задают большому количеству людей, чтобы узнать о мнениях",
      "wordTranslate": "опрос",
      "wordsPerExampleSentence": 13
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb9",
      "group": 3,
      "page": 0,
      "word": "target",
      "image": "files/01_1818.jpg",
      "audio": "files/01_1818.mp3",
      "audioMeaning": "files/01_1818_meaning.mp3",
      "audioExample": "files/01_1818_example.mp3",
      "textMeaning": "To <i>target</i> is to aim an attack at someone or something.",
      "textExample": "Scientists are looking for new drugs to <b>target</b> cancer cells.",
      "transcription": "[tάːrgit]",
      "textExampleTranslate": "Ученые ищут новые лекарства для нацеливания на раковые клетки",
      "textMeaningTranslate": "Таргетировать это нацеливать нападение на кого-то или что-то",
      "wordTranslate": "мишень",
      "wordsPerExampleSentence": 10
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbbb",
      "group": 3,
      "page": 0,
      "word": "trend",
      "image": "files/01_1819.jpg",
      "audio": "files/01_1819.mp3",
      "audioMeaning": "files/01_1819_meaning.mp3",
      "audioExample": "files/01_1819_example.mp3",
      "textMeaning": "A <i>trend</i> is a general tendency in the way a situation is changing or developing.",
      "textExample": "Lucy likes to think she started this fashion <b>trend</b>.",
      "transcription": "[trend]",
      "textExampleTranslate": "Люси нравится думать, что она начала эту модную тенденцию",
      "textMeaningTranslate": "Тенденция - это общая тенденция изменения или развития ситуации",
      "wordTranslate": "тренд",
      "wordsPerExampleSentence": 9
    }
  ],
  3: [
    {
      "id": "5e9f5ee35eb9e72bc21afba9",
      "group": 3,
      "page": 0,
      "word": "accountable",
      "image": "files/01_1801.jpg",
      "audio": "files/01_1801.mp3",
      "audioMeaning": "files/01_1801_meaning.mp3",
      "audioExample": "files/01_1801_example.mp3",
      "textMeaning": "When someone is <i>accountable</i>, he or she is responsible for the effects of his or her actions.",
      "textExample": "Political leaders are <b>accountable</b> to the people they represent.",
      "transcription": "[əkáuntəbl]",
      "textExampleTranslate": "Политические лидеры ответственны перед людьми, которых они представляют",
      "textMeaningTranslate": "Когда кто-то несет ответственность, он или она несут ответственность за последствия своих действий",
      "wordTranslate": "подотчетны",
      "wordsPerExampleSentence": 9
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbab",
      "group": 3,
      "page": 0,
      "word": "coin",
      "image": "files/01_1804.jpg",
      "audio": "files/01_1804.mp3",
      "audioMeaning": "files/01_1804_meaning.mp3",
      "audioExample": "files/01_1804_example.mp3",
      "textMeaning": "To <i>coin</i> is to create a new word or phrase that other people begin to use.",
      "textExample": "The coach <b>coined</b> the phrase, “There is no ‘I’ in team.”",
      "transcription": "[kɔin]",
      "textExampleTranslate": "Тренер придумал фразу 'В команде нет 'я''",
      "textMeaningTranslate": "Монета означает создание нового слова или фразы, которые начинают использовать другие люди",
      "wordTranslate": "монета",
      "wordsPerExampleSentence": 11
    },
    {
      "id": "5e9f5ee35eb9e72bc21afba8",
      "group": 3,
      "page": 0,
      "word": "addictive",
      "image": "files/01_1802.jpg",
      "audio": "files/01_1802.mp3",
      "audioMeaning": "files/01_1802_meaning.mp3",
      "audioExample": "files/01_1802_example.mp3",
      "textMeaning": "If something is <i>addictive</i>, it is hard to stop doing.",
      "textExample": "I think this game is very <b>addictive</b>.",
      "transcription": "[ədíktiv]",
      "textExampleTranslate": "Я думаю, что эта игра очень затягивает",
      "textMeaningTranslate": "Если что-то вызывает привыкание, трудно перестать делать",
      "wordTranslate": "привыкание",
      "wordsPerExampleSentence": 7
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbaa",
      "group": 3,
      "page": 0,
      "word": "agenda",
      "image": "files/01_1803.jpg",
      "audio": "files/01_1803.mp3",
      "audioMeaning": "files/01_1803_meaning.mp3",
      "audioExample": "files/01_1803_example.mp3",
      "textMeaning": "An <i>agenda</i> is a plan or goal that guides someone’s behavior.",
      "textExample": "The man is pushing his questionable <b>agenda</b> on his colleagues.",
      "transcription": "[ədʒéndə]",
      "textExampleTranslate": "Человек выдвигает свою сомнительную повестку дня на своих коллег",
      "textMeaningTranslate": "Повестка дня - это план или цель, определяющая поведение человека",
      "wordTranslate": "повестка дня",
      "wordsPerExampleSentence": 10
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbad",
      "group": 3,
      "page": 0,
      "word": "depression",
      "image": "files/01_1806.jpg",
      "audio": "files/01_1806.mp3",
      "audioMeaning": "files/01_1806_meaning.mp3",
      "audioExample": "files/01_1806_example.mp3",
      "textMeaning": "<i>Depression</i> is a medical condition that makes a person very unhappy for long periods of time.",
      "textExample": "Ron decided to get help for his <b>depression</b>.",
      "transcription": "[dipréʃən]",
      "textExampleTranslate": "Рон решил получить помощь от депрессии",
      "textMeaningTranslate": "Депрессия - это заболевание, которое делает человека очень несчастным в течение длительного времени",
      "wordTranslate": "депрессия",
      "wordsPerExampleSentence": 8
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbac",
      "group": 3,
      "page": 0,
      "word": "correlate",
      "image": "files/01_1805.jpg",
      "audio": "files/01_1805.mp3",
      "audioMeaning": "files/01_1805_meaning.mp3",
      "audioExample": "files/01_1805_example.mp3",
      "textMeaning": "To <i>correlate</i> is to have a close connection to something.",
      "textExample": "Scientists believe that brain size might <b>correlate</b> with intelligence.",
      "transcription": "[kɔ́ːrəlèit]",
      "textExampleTranslate": "Ученые считают, что размер мозга может коррелировать с интеллектом",
      "textMeaningTranslate": "Соотносить это значит иметь тесную связь с чем-то",
      "wordTranslate": "коррелят",
      "wordsPerExampleSentence": 9
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbae",
      "group": 3,
      "page": 0,
      "word": "digital",
      "image": "files/01_1807.jpg",
      "audio": "files/01_1807.mp3",
      "audioMeaning": "files/01_1807_meaning.mp3",
      "audioExample": "files/01_1807_example.mp3",
      "textMeaning": "When something is <i>digital</i>, it is characterized by computer technology.",
      "textExample": "Students prefer to take notes on their laptops and other <b>digital</b> devices.",
      "transcription": "[dídʒətl]",
      "textExampleTranslate": "Студенты предпочитают делать заметки на своих ноутбуках и других цифровых устройствах",
      "textMeaningTranslate": "Когда что-то является цифровым, оно характеризуется компьютерными технологиями",
      "wordTranslate": "цифровой",
      "wordsPerExampleSentence": 12
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbaf",
      "group": 3,
      "page": 0,
      "word": "keyboard",
      "image": "files/01_1809.jpg",
      "audio": "files/01_1809.mp3",
      "audioMeaning": "files/01_1809_meaning.mp3",
      "audioExample": "files/01_1809_example.mp3",
      "textMeaning": "A <i>keyboard</i> has buttons marked with letters and numbers that are pressed to put information into a computer.",
      "textExample": "Paul spilled coffee all over his <b>keyboard</b>.",
      "transcription": "[kíbɔːrd]",
      "textExampleTranslate": "Пол разлил кофе по всей клавиатуре",
      "textMeaningTranslate": "На клавиатуре есть кнопки, помеченные буквами и цифрами, которые нажимаются для ввода информации в компьютер",
      "wordTranslate": "клавиатура",
      "wordsPerExampleSentence": 7
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb0",
      "group": 3,
      "page": 0,
      "word": "importance",
      "image": "files/01_1808.jpg",
      "audio": "files/01_1808.mp3",
      "audioMeaning": "files/01_1808_meaning.mp3",
      "audioExample": "files/01_1808_example.mp3",
      "textMeaning": "<i>Importance</i> is the quality or state of being important, valuable, or significant.",
      "textExample": "The professor lectured the students on the <b>importance</b> of communication strategies.",
      "transcription": "[impɔ́ːrtəns]",
      "textExampleTranslate": "Профессор читал лекции студентам о важности коммуникационных стратегий",
      "textMeaningTranslate": "Важность - это качество или состояние важности, ценности или значимости",
      "wordTranslate": "значение",
      "wordsPerExampleSentence": 11
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb2",
      "group": 3,
      "page": 0,
      "word": "media",
      "image": "files/01_1811.jpg",
      "audio": "files/01_1811.mp3",
      "audioMeaning": "files/01_1811_meaning.mp3",
      "audioExample": "files/01_1811_example.mp3",
      "textMeaning": "<i>Media</i> is the different ways of entertaining and giving information to the public.",
      "textExample": "Many people like to express their opinions online using social <b>media</b>.",
      "transcription": "[míːdiə]",
      "textExampleTranslate": "Многие люди хотели бы выразить свое мнение в Интернете с помощью социальных сетей",
      "textMeaningTranslate": "СМИ - это разные способы развлечения и предоставления информации общественности",
      "wordTranslate": "CМИ",
      "wordsPerExampleSentence": 11
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb1",
      "group": 3,
      "page": 0,
      "word": "loneliness",
      "image": "files/01_1810.jpg",
      "audio": "files/01_1810.mp3",
      "audioMeaning": "files/01_1810_meaning.mp3",
      "audioExample": "files/01_1810_example.mp3",
      "textMeaning": "<i>Loneliness</i> is the unhappiness that is felt by someone if they do not have any friends.",
      "textExample": "Many people join social clubs to escape <b>loneliness</b>.",
      "transcription": "[lóunlinis]",
      "textExampleTranslate": "Многие люди вступают в социальные клубы, чтобы избежать одиночества",
      "textMeaningTranslate": "Одиночество - это несчастье, которое кто-то чувствует, если у него нет друзей",
      "wordTranslate": "одиночество",
      "wordsPerExampleSentence": 8
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb3",
      "group": 3,
      "page": 0,
      "word": "platform",
      "image": "files/01_1812.jpg",
      "audio": "files/01_1812.mp3",
      "audioMeaning": "files/01_1812_meaning.mp3",
      "audioExample": "files/01_1812_example.mp3",
      "textMeaning": "A <i>platform</i> is something that allows someone to tell a large number of people about an idea, product, etc.",
      "textExample": "The band uses their music as a <b>platform</b> to express their political beliefs.",
      "transcription": "[plǽtfɔːrm]",
      "textExampleTranslate": "Группа использует свою музыку в качестве платформы для выражения своих политических убеждений",
      "textMeaningTranslate": "Платформа - это то, что позволяет кому-то рассказать большому количеству людей об идее, продукте и т. Д",
      "wordTranslate": "платформа",
      "wordsPerExampleSentence": 13
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb4",
      "group": 3,
      "page": 0,
      "word": "presence",
      "image": "files/01_1814.jpg",
      "audio": "files/01_1814.mp3",
      "audioMeaning": "files/01_1814_meaning.mp3",
      "audioExample": "files/01_1814_example.mp3",
      "textMeaning": "<i>Presence</i> is when someone or something is present in a particular place.",
      "textExample": "The researcher discovered the <b>presence</b> of bacteria in the water sample.",
      "transcription": "[prézns]",
      "textExampleTranslate": "Исследователь обнаружил присутствие бактерий в пробе воды",
      "textMeaningTranslate": "Присутствие - это когда кто-то или что-то присутствует в определенном месте",
      "wordTranslate": "присутствие",
      "wordsPerExampleSentence": 11
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb5",
      "group": 3,
      "page": 0,
      "word": "poor",
      "image": "files/01_1813.jpg",
      "audio": "files/01_1813.mp3",
      "audioMeaning": "files/01_1813_meaning.mp3",
      "audioExample": "files/01_1813_example.mp3",
      "textMeaning": "When something is <i>poor</i>, it is not as good as it could or should be.",
      "textExample": "The condition of the sidewalk is very <b>poor</b>.",
      "transcription": "[puər]",
      "textExampleTranslate": "Состояние тротуара очень плохое",
      "textMeaningTranslate": "Когда что-то плохое, это не так хорошо, как могло бы или должно быть",
      "wordTranslate": "бедных",
      "wordsPerExampleSentence": 8
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb7",
      "group": 3,
      "page": 0,
      "word": "surge",
      "image": "files/01_1816.jpg",
      "audio": "files/01_1816.mp3",
      "audioMeaning": "files/01_1816_meaning.mp3",
      "audioExample": "files/01_1816_example.mp3",
      "textMeaning": "A <i>surge</i> is a sudden, large increase in something.",
      "textExample": "All at once, there was a <b>surge</b> of runners at the finish line.",
      "transcription": "[səːrdʒ]",
      "textExampleTranslate": "Внезапно на финише всплеск бегунов",
      "textMeaningTranslate": "Волна - это внезапное, значительное увеличение чего-либо",
      "wordTranslate": "всплеск",
      "wordsPerExampleSentence": 13
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb6",
      "group": 3,
      "page": 0,
      "word": "subject",
      "image": "files/01_1815.jpg",
      "audio": "files/01_1815.mp3",
      "audioMeaning": "files/01_1815_meaning.mp3",
      "audioExample": "files/01_1815_example.mp3",
      "textMeaning": "To <i>subject</i> is to cause or force someone or something to experience something harmful or unpleasant.",
      "textExample": "The location of the trees will <b>subject</b> them to strong winds from the hurricane.",
      "transcription": "[sΛbdʒikt]",
      "textExampleTranslate": "Расположение деревьев подвергнет их сильным ветрам от урагана",
      "textMeaningTranslate": "Субъект должен вызывать или заставлять кого-то или что-либо испытывать что-то вредное или неприятное",
      "wordTranslate": "тема",
      "wordsPerExampleSentence": 14
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbba",
      "group": 3,
      "page": 0,
      "word": "validate",
      "image": "files/01_1820.jpg",
      "audio": "files/01_1820.mp3",
      "audioMeaning": "files/01_1820_meaning.mp3",
      "audioExample": "files/01_1820_example.mp3",
      "textMeaning": "To <i>validate</i> is to make someone feel that his or her ideas and feelings are respected.",
      "textExample": "Winning first prize will <b>validate</b> all of Tony’s hard work.",
      "transcription": "[vǽlədèit]",
      "textExampleTranslate": "Получение первого приза подтвердит всю тяжелую работу Тони",
      "textMeaningTranslate": "Подтвердить - значит заставить кого-то почувствовать, что его или ее идеи и чувства уважают",
      "wordTranslate": "проверка",
      "wordsPerExampleSentence": 10
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb8",
      "group": 3,
      "page": 0,
      "word": "survey",
      "image": "files/01_1817.jpg",
      "audio": "files/01_1817.mp3",
      "audioMeaning": "files/01_1817_meaning.mp3",
      "audioExample": "files/01_1817_example.mp3",
      "textMeaning": "A <i>survey</i> is a set of questions that are asked to a large number of people in order to find out about opinions.",
      "textExample": "I filled out a <b>survey</b> about my shopping experience at the department store.",
      "transcription": "[sərvéi]",
      "textExampleTranslate": "Я заполнил опрос о моем опыте покупок в универмаге",
      "textMeaningTranslate": "Опрос - это набор вопросов, которые задают большому количеству людей, чтобы узнать о мнениях",
      "wordTranslate": "опрос",
      "wordsPerExampleSentence": 13
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb9",
      "group": 3,
      "page": 0,
      "word": "target",
      "image": "files/01_1818.jpg",
      "audio": "files/01_1818.mp3",
      "audioMeaning": "files/01_1818_meaning.mp3",
      "audioExample": "files/01_1818_example.mp3",
      "textMeaning": "To <i>target</i> is to aim an attack at someone or something.",
      "textExample": "Scientists are looking for new drugs to <b>target</b> cancer cells.",
      "transcription": "[tάːrgit]",
      "textExampleTranslate": "Ученые ищут новые лекарства для нацеливания на раковые клетки",
      "textMeaningTranslate": "Таргетировать это нацеливать нападение на кого-то или что-то",
      "wordTranslate": "мишень",
      "wordsPerExampleSentence": 10
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbbb",
      "group": 3,
      "page": 0,
      "word": "trend",
      "image": "files/01_1819.jpg",
      "audio": "files/01_1819.mp3",
      "audioMeaning": "files/01_1819_meaning.mp3",
      "audioExample": "files/01_1819_example.mp3",
      "textMeaning": "A <i>trend</i> is a general tendency in the way a situation is changing or developing.",
      "textExample": "Lucy likes to think she started this fashion <b>trend</b>.",
      "transcription": "[trend]",
      "textExampleTranslate": "Люси нравится думать, что она начала эту модную тенденцию",
      "textMeaningTranslate": "Тенденция - это общая тенденция изменения или развития ситуации",
      "wordTranslate": "тренд",
      "wordsPerExampleSentence": 9
    }
  ],
  4: [
    {
      "id": "5e9f5ee35eb9e72bc21afba9",
      "group": 3,
      "page": 0,
      "word": "accountable",
      "image": "files/01_1801.jpg",
      "audio": "files/01_1801.mp3",
      "audioMeaning": "files/01_1801_meaning.mp3",
      "audioExample": "files/01_1801_example.mp3",
      "textMeaning": "When someone is <i>accountable</i>, he or she is responsible for the effects of his or her actions.",
      "textExample": "Political leaders are <b>accountable</b> to the people they represent.",
      "transcription": "[əkáuntəbl]",
      "textExampleTranslate": "Политические лидеры ответственны перед людьми, которых они представляют",
      "textMeaningTranslate": "Когда кто-то несет ответственность, он или она несут ответственность за последствия своих действий",
      "wordTranslate": "подотчетны",
      "wordsPerExampleSentence": 9
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbab",
      "group": 3,
      "page": 0,
      "word": "coin",
      "image": "files/01_1804.jpg",
      "audio": "files/01_1804.mp3",
      "audioMeaning": "files/01_1804_meaning.mp3",
      "audioExample": "files/01_1804_example.mp3",
      "textMeaning": "To <i>coin</i> is to create a new word or phrase that other people begin to use.",
      "textExample": "The coach <b>coined</b> the phrase, “There is no ‘I’ in team.”",
      "transcription": "[kɔin]",
      "textExampleTranslate": "Тренер придумал фразу 'В команде нет 'я''",
      "textMeaningTranslate": "Монета означает создание нового слова или фразы, которые начинают использовать другие люди",
      "wordTranslate": "монета",
      "wordsPerExampleSentence": 11
    },
    {
      "id": "5e9f5ee35eb9e72bc21afba8",
      "group": 3,
      "page": 0,
      "word": "addictive",
      "image": "files/01_1802.jpg",
      "audio": "files/01_1802.mp3",
      "audioMeaning": "files/01_1802_meaning.mp3",
      "audioExample": "files/01_1802_example.mp3",
      "textMeaning": "If something is <i>addictive</i>, it is hard to stop doing.",
      "textExample": "I think this game is very <b>addictive</b>.",
      "transcription": "[ədíktiv]",
      "textExampleTranslate": "Я думаю, что эта игра очень затягивает",
      "textMeaningTranslate": "Если что-то вызывает привыкание, трудно перестать делать",
      "wordTranslate": "привыкание",
      "wordsPerExampleSentence": 7
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbaa",
      "group": 3,
      "page": 0,
      "word": "agenda",
      "image": "files/01_1803.jpg",
      "audio": "files/01_1803.mp3",
      "audioMeaning": "files/01_1803_meaning.mp3",
      "audioExample": "files/01_1803_example.mp3",
      "textMeaning": "An <i>agenda</i> is a plan or goal that guides someone’s behavior.",
      "textExample": "The man is pushing his questionable <b>agenda</b> on his colleagues.",
      "transcription": "[ədʒéndə]",
      "textExampleTranslate": "Человек выдвигает свою сомнительную повестку дня на своих коллег",
      "textMeaningTranslate": "Повестка дня - это план или цель, определяющая поведение человека",
      "wordTranslate": "повестка дня",
      "wordsPerExampleSentence": 10
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbad",
      "group": 3,
      "page": 0,
      "word": "depression",
      "image": "files/01_1806.jpg",
      "audio": "files/01_1806.mp3",
      "audioMeaning": "files/01_1806_meaning.mp3",
      "audioExample": "files/01_1806_example.mp3",
      "textMeaning": "<i>Depression</i> is a medical condition that makes a person very unhappy for long periods of time.",
      "textExample": "Ron decided to get help for his <b>depression</b>.",
      "transcription": "[dipréʃən]",
      "textExampleTranslate": "Рон решил получить помощь от депрессии",
      "textMeaningTranslate": "Депрессия - это заболевание, которое делает человека очень несчастным в течение длительного времени",
      "wordTranslate": "депрессия",
      "wordsPerExampleSentence": 8
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbac",
      "group": 3,
      "page": 0,
      "word": "correlate",
      "image": "files/01_1805.jpg",
      "audio": "files/01_1805.mp3",
      "audioMeaning": "files/01_1805_meaning.mp3",
      "audioExample": "files/01_1805_example.mp3",
      "textMeaning": "To <i>correlate</i> is to have a close connection to something.",
      "textExample": "Scientists believe that brain size might <b>correlate</b> with intelligence.",
      "transcription": "[kɔ́ːrəlèit]",
      "textExampleTranslate": "Ученые считают, что размер мозга может коррелировать с интеллектом",
      "textMeaningTranslate": "Соотносить это значит иметь тесную связь с чем-то",
      "wordTranslate": "коррелят",
      "wordsPerExampleSentence": 9
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbae",
      "group": 3,
      "page": 0,
      "word": "digital",
      "image": "files/01_1807.jpg",
      "audio": "files/01_1807.mp3",
      "audioMeaning": "files/01_1807_meaning.mp3",
      "audioExample": "files/01_1807_example.mp3",
      "textMeaning": "When something is <i>digital</i>, it is characterized by computer technology.",
      "textExample": "Students prefer to take notes on their laptops and other <b>digital</b> devices.",
      "transcription": "[dídʒətl]",
      "textExampleTranslate": "Студенты предпочитают делать заметки на своих ноутбуках и других цифровых устройствах",
      "textMeaningTranslate": "Когда что-то является цифровым, оно характеризуется компьютерными технологиями",
      "wordTranslate": "цифровой",
      "wordsPerExampleSentence": 12
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbaf",
      "group": 3,
      "page": 0,
      "word": "keyboard",
      "image": "files/01_1809.jpg",
      "audio": "files/01_1809.mp3",
      "audioMeaning": "files/01_1809_meaning.mp3",
      "audioExample": "files/01_1809_example.mp3",
      "textMeaning": "A <i>keyboard</i> has buttons marked with letters and numbers that are pressed to put information into a computer.",
      "textExample": "Paul spilled coffee all over his <b>keyboard</b>.",
      "transcription": "[kíbɔːrd]",
      "textExampleTranslate": "Пол разлил кофе по всей клавиатуре",
      "textMeaningTranslate": "На клавиатуре есть кнопки, помеченные буквами и цифрами, которые нажимаются для ввода информации в компьютер",
      "wordTranslate": "клавиатура",
      "wordsPerExampleSentence": 7
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb0",
      "group": 3,
      "page": 0,
      "word": "importance",
      "image": "files/01_1808.jpg",
      "audio": "files/01_1808.mp3",
      "audioMeaning": "files/01_1808_meaning.mp3",
      "audioExample": "files/01_1808_example.mp3",
      "textMeaning": "<i>Importance</i> is the quality or state of being important, valuable, or significant.",
      "textExample": "The professor lectured the students on the <b>importance</b> of communication strategies.",
      "transcription": "[impɔ́ːrtəns]",
      "textExampleTranslate": "Профессор читал лекции студентам о важности коммуникационных стратегий",
      "textMeaningTranslate": "Важность - это качество или состояние важности, ценности или значимости",
      "wordTranslate": "значение",
      "wordsPerExampleSentence": 11
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb2",
      "group": 3,
      "page": 0,
      "word": "media",
      "image": "files/01_1811.jpg",
      "audio": "files/01_1811.mp3",
      "audioMeaning": "files/01_1811_meaning.mp3",
      "audioExample": "files/01_1811_example.mp3",
      "textMeaning": "<i>Media</i> is the different ways of entertaining and giving information to the public.",
      "textExample": "Many people like to express their opinions online using social <b>media</b>.",
      "transcription": "[míːdiə]",
      "textExampleTranslate": "Многие люди хотели бы выразить свое мнение в Интернете с помощью социальных сетей",
      "textMeaningTranslate": "СМИ - это разные способы развлечения и предоставления информации общественности",
      "wordTranslate": "CМИ",
      "wordsPerExampleSentence": 11
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb1",
      "group": 3,
      "page": 0,
      "word": "loneliness",
      "image": "files/01_1810.jpg",
      "audio": "files/01_1810.mp3",
      "audioMeaning": "files/01_1810_meaning.mp3",
      "audioExample": "files/01_1810_example.mp3",
      "textMeaning": "<i>Loneliness</i> is the unhappiness that is felt by someone if they do not have any friends.",
      "textExample": "Many people join social clubs to escape <b>loneliness</b>.",
      "transcription": "[lóunlinis]",
      "textExampleTranslate": "Многие люди вступают в социальные клубы, чтобы избежать одиночества",
      "textMeaningTranslate": "Одиночество - это несчастье, которое кто-то чувствует, если у него нет друзей",
      "wordTranslate": "одиночество",
      "wordsPerExampleSentence": 8
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb3",
      "group": 3,
      "page": 0,
      "word": "platform",
      "image": "files/01_1812.jpg",
      "audio": "files/01_1812.mp3",
      "audioMeaning": "files/01_1812_meaning.mp3",
      "audioExample": "files/01_1812_example.mp3",
      "textMeaning": "A <i>platform</i> is something that allows someone to tell a large number of people about an idea, product, etc.",
      "textExample": "The band uses their music as a <b>platform</b> to express their political beliefs.",
      "transcription": "[plǽtfɔːrm]",
      "textExampleTranslate": "Группа использует свою музыку в качестве платформы для выражения своих политических убеждений",
      "textMeaningTranslate": "Платформа - это то, что позволяет кому-то рассказать большому количеству людей об идее, продукте и т. Д",
      "wordTranslate": "платформа",
      "wordsPerExampleSentence": 13
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb4",
      "group": 3,
      "page": 0,
      "word": "presence",
      "image": "files/01_1814.jpg",
      "audio": "files/01_1814.mp3",
      "audioMeaning": "files/01_1814_meaning.mp3",
      "audioExample": "files/01_1814_example.mp3",
      "textMeaning": "<i>Presence</i> is when someone or something is present in a particular place.",
      "textExample": "The researcher discovered the <b>presence</b> of bacteria in the water sample.",
      "transcription": "[prézns]",
      "textExampleTranslate": "Исследователь обнаружил присутствие бактерий в пробе воды",
      "textMeaningTranslate": "Присутствие - это когда кто-то или что-то присутствует в определенном месте",
      "wordTranslate": "присутствие",
      "wordsPerExampleSentence": 11
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb5",
      "group": 3,
      "page": 0,
      "word": "poor",
      "image": "files/01_1813.jpg",
      "audio": "files/01_1813.mp3",
      "audioMeaning": "files/01_1813_meaning.mp3",
      "audioExample": "files/01_1813_example.mp3",
      "textMeaning": "When something is <i>poor</i>, it is not as good as it could or should be.",
      "textExample": "The condition of the sidewalk is very <b>poor</b>.",
      "transcription": "[puər]",
      "textExampleTranslate": "Состояние тротуара очень плохое",
      "textMeaningTranslate": "Когда что-то плохое, это не так хорошо, как могло бы или должно быть",
      "wordTranslate": "бедных",
      "wordsPerExampleSentence": 8
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb7",
      "group": 3,
      "page": 0,
      "word": "surge",
      "image": "files/01_1816.jpg",
      "audio": "files/01_1816.mp3",
      "audioMeaning": "files/01_1816_meaning.mp3",
      "audioExample": "files/01_1816_example.mp3",
      "textMeaning": "A <i>surge</i> is a sudden, large increase in something.",
      "textExample": "All at once, there was a <b>surge</b> of runners at the finish line.",
      "transcription": "[səːrdʒ]",
      "textExampleTranslate": "Внезапно на финише всплеск бегунов",
      "textMeaningTranslate": "Волна - это внезапное, значительное увеличение чего-либо",
      "wordTranslate": "всплеск",
      "wordsPerExampleSentence": 13
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb6",
      "group": 3,
      "page": 0,
      "word": "subject",
      "image": "files/01_1815.jpg",
      "audio": "files/01_1815.mp3",
      "audioMeaning": "files/01_1815_meaning.mp3",
      "audioExample": "files/01_1815_example.mp3",
      "textMeaning": "To <i>subject</i> is to cause or force someone or something to experience something harmful or unpleasant.",
      "textExample": "The location of the trees will <b>subject</b> them to strong winds from the hurricane.",
      "transcription": "[sΛbdʒikt]",
      "textExampleTranslate": "Расположение деревьев подвергнет их сильным ветрам от урагана",
      "textMeaningTranslate": "Субъект должен вызывать или заставлять кого-то или что-либо испытывать что-то вредное или неприятное",
      "wordTranslate": "тема",
      "wordsPerExampleSentence": 14
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbba",
      "group": 3,
      "page": 0,
      "word": "validate",
      "image": "files/01_1820.jpg",
      "audio": "files/01_1820.mp3",
      "audioMeaning": "files/01_1820_meaning.mp3",
      "audioExample": "files/01_1820_example.mp3",
      "textMeaning": "To <i>validate</i> is to make someone feel that his or her ideas and feelings are respected.",
      "textExample": "Winning first prize will <b>validate</b> all of Tony’s hard work.",
      "transcription": "[vǽlədèit]",
      "textExampleTranslate": "Получение первого приза подтвердит всю тяжелую работу Тони",
      "textMeaningTranslate": "Подтвердить - значит заставить кого-то почувствовать, что его или ее идеи и чувства уважают",
      "wordTranslate": "проверка",
      "wordsPerExampleSentence": 10
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb8",
      "group": 3,
      "page": 0,
      "word": "survey",
      "image": "files/01_1817.jpg",
      "audio": "files/01_1817.mp3",
      "audioMeaning": "files/01_1817_meaning.mp3",
      "audioExample": "files/01_1817_example.mp3",
      "textMeaning": "A <i>survey</i> is a set of questions that are asked to a large number of people in order to find out about opinions.",
      "textExample": "I filled out a <b>survey</b> about my shopping experience at the department store.",
      "transcription": "[sərvéi]",
      "textExampleTranslate": "Я заполнил опрос о моем опыте покупок в универмаге",
      "textMeaningTranslate": "Опрос - это набор вопросов, которые задают большому количеству людей, чтобы узнать о мнениях",
      "wordTranslate": "опрос",
      "wordsPerExampleSentence": 13
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb9",
      "group": 3,
      "page": 0,
      "word": "target",
      "image": "files/01_1818.jpg",
      "audio": "files/01_1818.mp3",
      "audioMeaning": "files/01_1818_meaning.mp3",
      "audioExample": "files/01_1818_example.mp3",
      "textMeaning": "To <i>target</i> is to aim an attack at someone or something.",
      "textExample": "Scientists are looking for new drugs to <b>target</b> cancer cells.",
      "transcription": "[tάːrgit]",
      "textExampleTranslate": "Ученые ищут новые лекарства для нацеливания на раковые клетки",
      "textMeaningTranslate": "Таргетировать это нацеливать нападение на кого-то или что-то",
      "wordTranslate": "мишень",
      "wordsPerExampleSentence": 10
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbbb",
      "group": 3,
      "page": 0,
      "word": "trend",
      "image": "files/01_1819.jpg",
      "audio": "files/01_1819.mp3",
      "audioMeaning": "files/01_1819_meaning.mp3",
      "audioExample": "files/01_1819_example.mp3",
      "textMeaning": "A <i>trend</i> is a general tendency in the way a situation is changing or developing.",
      "textExample": "Lucy likes to think she started this fashion <b>trend</b>.",
      "transcription": "[trend]",
      "textExampleTranslate": "Люси нравится думать, что она начала эту модную тенденцию",
      "textMeaningTranslate": "Тенденция - это общая тенденция изменения или развития ситуации",
      "wordTranslate": "тренд",
      "wordsPerExampleSentence": 9
    }
  ],
  5: [
    {
      "id": "5e9f5ee35eb9e72bc21afba9",
      "group": 3,
      "page": 0,
      "word": "accountable",
      "image": "files/01_1801.jpg",
      "audio": "files/01_1801.mp3",
      "audioMeaning": "files/01_1801_meaning.mp3",
      "audioExample": "files/01_1801_example.mp3",
      "textMeaning": "When someone is <i>accountable</i>, he or she is responsible for the effects of his or her actions.",
      "textExample": "Political leaders are <b>accountable</b> to the people they represent.",
      "transcription": "[əkáuntəbl]",
      "textExampleTranslate": "Политические лидеры ответственны перед людьми, которых они представляют",
      "textMeaningTranslate": "Когда кто-то несет ответственность, он или она несут ответственность за последствия своих действий",
      "wordTranslate": "подотчетны",
      "wordsPerExampleSentence": 9
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbab",
      "group": 3,
      "page": 0,
      "word": "coin",
      "image": "files/01_1804.jpg",
      "audio": "files/01_1804.mp3",
      "audioMeaning": "files/01_1804_meaning.mp3",
      "audioExample": "files/01_1804_example.mp3",
      "textMeaning": "To <i>coin</i> is to create a new word or phrase that other people begin to use.",
      "textExample": "The coach <b>coined</b> the phrase, “There is no ‘I’ in team.”",
      "transcription": "[kɔin]",
      "textExampleTranslate": "Тренер придумал фразу 'В команде нет 'я''",
      "textMeaningTranslate": "Монета означает создание нового слова или фразы, которые начинают использовать другие люди",
      "wordTranslate": "монета",
      "wordsPerExampleSentence": 11
    },
    {
      "id": "5e9f5ee35eb9e72bc21afba8",
      "group": 3,
      "page": 0,
      "word": "addictive",
      "image": "files/01_1802.jpg",
      "audio": "files/01_1802.mp3",
      "audioMeaning": "files/01_1802_meaning.mp3",
      "audioExample": "files/01_1802_example.mp3",
      "textMeaning": "If something is <i>addictive</i>, it is hard to stop doing.",
      "textExample": "I think this game is very <b>addictive</b>.",
      "transcription": "[ədíktiv]",
      "textExampleTranslate": "Я думаю, что эта игра очень затягивает",
      "textMeaningTranslate": "Если что-то вызывает привыкание, трудно перестать делать",
      "wordTranslate": "привыкание",
      "wordsPerExampleSentence": 7
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbaa",
      "group": 3,
      "page": 0,
      "word": "agenda",
      "image": "files/01_1803.jpg",
      "audio": "files/01_1803.mp3",
      "audioMeaning": "files/01_1803_meaning.mp3",
      "audioExample": "files/01_1803_example.mp3",
      "textMeaning": "An <i>agenda</i> is a plan or goal that guides someone’s behavior.",
      "textExample": "The man is pushing his questionable <b>agenda</b> on his colleagues.",
      "transcription": "[ədʒéndə]",
      "textExampleTranslate": "Человек выдвигает свою сомнительную повестку дня на своих коллег",
      "textMeaningTranslate": "Повестка дня - это план или цель, определяющая поведение человека",
      "wordTranslate": "повестка дня",
      "wordsPerExampleSentence": 10
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbad",
      "group": 3,
      "page": 0,
      "word": "depression",
      "image": "files/01_1806.jpg",
      "audio": "files/01_1806.mp3",
      "audioMeaning": "files/01_1806_meaning.mp3",
      "audioExample": "files/01_1806_example.mp3",
      "textMeaning": "<i>Depression</i> is a medical condition that makes a person very unhappy for long periods of time.",
      "textExample": "Ron decided to get help for his <b>depression</b>.",
      "transcription": "[dipréʃən]",
      "textExampleTranslate": "Рон решил получить помощь от депрессии",
      "textMeaningTranslate": "Депрессия - это заболевание, которое делает человека очень несчастным в течение длительного времени",
      "wordTranslate": "депрессия",
      "wordsPerExampleSentence": 8
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbac",
      "group": 3,
      "page": 0,
      "word": "correlate",
      "image": "files/01_1805.jpg",
      "audio": "files/01_1805.mp3",
      "audioMeaning": "files/01_1805_meaning.mp3",
      "audioExample": "files/01_1805_example.mp3",
      "textMeaning": "To <i>correlate</i> is to have a close connection to something.",
      "textExample": "Scientists believe that brain size might <b>correlate</b> with intelligence.",
      "transcription": "[kɔ́ːrəlèit]",
      "textExampleTranslate": "Ученые считают, что размер мозга может коррелировать с интеллектом",
      "textMeaningTranslate": "Соотносить это значит иметь тесную связь с чем-то",
      "wordTranslate": "коррелят",
      "wordsPerExampleSentence": 9
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbae",
      "group": 3,
      "page": 0,
      "word": "digital",
      "image": "files/01_1807.jpg",
      "audio": "files/01_1807.mp3",
      "audioMeaning": "files/01_1807_meaning.mp3",
      "audioExample": "files/01_1807_example.mp3",
      "textMeaning": "When something is <i>digital</i>, it is characterized by computer technology.",
      "textExample": "Students prefer to take notes on their laptops and other <b>digital</b> devices.",
      "transcription": "[dídʒətl]",
      "textExampleTranslate": "Студенты предпочитают делать заметки на своих ноутбуках и других цифровых устройствах",
      "textMeaningTranslate": "Когда что-то является цифровым, оно характеризуется компьютерными технологиями",
      "wordTranslate": "цифровой",
      "wordsPerExampleSentence": 12
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbaf",
      "group": 3,
      "page": 0,
      "word": "keyboard",
      "image": "files/01_1809.jpg",
      "audio": "files/01_1809.mp3",
      "audioMeaning": "files/01_1809_meaning.mp3",
      "audioExample": "files/01_1809_example.mp3",
      "textMeaning": "A <i>keyboard</i> has buttons marked with letters and numbers that are pressed to put information into a computer.",
      "textExample": "Paul spilled coffee all over his <b>keyboard</b>.",
      "transcription": "[kíbɔːrd]",
      "textExampleTranslate": "Пол разлил кофе по всей клавиатуре",
      "textMeaningTranslate": "На клавиатуре есть кнопки, помеченные буквами и цифрами, которые нажимаются для ввода информации в компьютер",
      "wordTranslate": "клавиатура",
      "wordsPerExampleSentence": 7
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb0",
      "group": 3,
      "page": 0,
      "word": "importance",
      "image": "files/01_1808.jpg",
      "audio": "files/01_1808.mp3",
      "audioMeaning": "files/01_1808_meaning.mp3",
      "audioExample": "files/01_1808_example.mp3",
      "textMeaning": "<i>Importance</i> is the quality or state of being important, valuable, or significant.",
      "textExample": "The professor lectured the students on the <b>importance</b> of communication strategies.",
      "transcription": "[impɔ́ːrtəns]",
      "textExampleTranslate": "Профессор читал лекции студентам о важности коммуникационных стратегий",
      "textMeaningTranslate": "Важность - это качество или состояние важности, ценности или значимости",
      "wordTranslate": "значение",
      "wordsPerExampleSentence": 11
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb2",
      "group": 3,
      "page": 0,
      "word": "media",
      "image": "files/01_1811.jpg",
      "audio": "files/01_1811.mp3",
      "audioMeaning": "files/01_1811_meaning.mp3",
      "audioExample": "files/01_1811_example.mp3",
      "textMeaning": "<i>Media</i> is the different ways of entertaining and giving information to the public.",
      "textExample": "Many people like to express their opinions online using social <b>media</b>.",
      "transcription": "[míːdiə]",
      "textExampleTranslate": "Многие люди хотели бы выразить свое мнение в Интернете с помощью социальных сетей",
      "textMeaningTranslate": "СМИ - это разные способы развлечения и предоставления информации общественности",
      "wordTranslate": "CМИ",
      "wordsPerExampleSentence": 11
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb1",
      "group": 3,
      "page": 0,
      "word": "loneliness",
      "image": "files/01_1810.jpg",
      "audio": "files/01_1810.mp3",
      "audioMeaning": "files/01_1810_meaning.mp3",
      "audioExample": "files/01_1810_example.mp3",
      "textMeaning": "<i>Loneliness</i> is the unhappiness that is felt by someone if they do not have any friends.",
      "textExample": "Many people join social clubs to escape <b>loneliness</b>.",
      "transcription": "[lóunlinis]",
      "textExampleTranslate": "Многие люди вступают в социальные клубы, чтобы избежать одиночества",
      "textMeaningTranslate": "Одиночество - это несчастье, которое кто-то чувствует, если у него нет друзей",
      "wordTranslate": "одиночество",
      "wordsPerExampleSentence": 8
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb3",
      "group": 3,
      "page": 0,
      "word": "platform",
      "image": "files/01_1812.jpg",
      "audio": "files/01_1812.mp3",
      "audioMeaning": "files/01_1812_meaning.mp3",
      "audioExample": "files/01_1812_example.mp3",
      "textMeaning": "A <i>platform</i> is something that allows someone to tell a large number of people about an idea, product, etc.",
      "textExample": "The band uses their music as a <b>platform</b> to express their political beliefs.",
      "transcription": "[plǽtfɔːrm]",
      "textExampleTranslate": "Группа использует свою музыку в качестве платформы для выражения своих политических убеждений",
      "textMeaningTranslate": "Платформа - это то, что позволяет кому-то рассказать большому количеству людей об идее, продукте и т. Д",
      "wordTranslate": "платформа",
      "wordsPerExampleSentence": 13
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb4",
      "group": 3,
      "page": 0,
      "word": "presence",
      "image": "files/01_1814.jpg",
      "audio": "files/01_1814.mp3",
      "audioMeaning": "files/01_1814_meaning.mp3",
      "audioExample": "files/01_1814_example.mp3",
      "textMeaning": "<i>Presence</i> is when someone or something is present in a particular place.",
      "textExample": "The researcher discovered the <b>presence</b> of bacteria in the water sample.",
      "transcription": "[prézns]",
      "textExampleTranslate": "Исследователь обнаружил присутствие бактерий в пробе воды",
      "textMeaningTranslate": "Присутствие - это когда кто-то или что-то присутствует в определенном месте",
      "wordTranslate": "присутствие",
      "wordsPerExampleSentence": 11
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb5",
      "group": 3,
      "page": 0,
      "word": "poor",
      "image": "files/01_1813.jpg",
      "audio": "files/01_1813.mp3",
      "audioMeaning": "files/01_1813_meaning.mp3",
      "audioExample": "files/01_1813_example.mp3",
      "textMeaning": "When something is <i>poor</i>, it is not as good as it could or should be.",
      "textExample": "The condition of the sidewalk is very <b>poor</b>.",
      "transcription": "[puər]",
      "textExampleTranslate": "Состояние тротуара очень плохое",
      "textMeaningTranslate": "Когда что-то плохое, это не так хорошо, как могло бы или должно быть",
      "wordTranslate": "бедных",
      "wordsPerExampleSentence": 8
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb7",
      "group": 3,
      "page": 0,
      "word": "surge",
      "image": "files/01_1816.jpg",
      "audio": "files/01_1816.mp3",
      "audioMeaning": "files/01_1816_meaning.mp3",
      "audioExample": "files/01_1816_example.mp3",
      "textMeaning": "A <i>surge</i> is a sudden, large increase in something.",
      "textExample": "All at once, there was a <b>surge</b> of runners at the finish line.",
      "transcription": "[səːrdʒ]",
      "textExampleTranslate": "Внезапно на финише всплеск бегунов",
      "textMeaningTranslate": "Волна - это внезапное, значительное увеличение чего-либо",
      "wordTranslate": "всплеск",
      "wordsPerExampleSentence": 13
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb6",
      "group": 3,
      "page": 0,
      "word": "subject",
      "image": "files/01_1815.jpg",
      "audio": "files/01_1815.mp3",
      "audioMeaning": "files/01_1815_meaning.mp3",
      "audioExample": "files/01_1815_example.mp3",
      "textMeaning": "To <i>subject</i> is to cause or force someone or something to experience something harmful or unpleasant.",
      "textExample": "The location of the trees will <b>subject</b> them to strong winds from the hurricane.",
      "transcription": "[sΛbdʒikt]",
      "textExampleTranslate": "Расположение деревьев подвергнет их сильным ветрам от урагана",
      "textMeaningTranslate": "Субъект должен вызывать или заставлять кого-то или что-либо испытывать что-то вредное или неприятное",
      "wordTranslate": "тема",
      "wordsPerExampleSentence": 14
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbba",
      "group": 3,
      "page": 0,
      "word": "validate",
      "image": "files/01_1820.jpg",
      "audio": "files/01_1820.mp3",
      "audioMeaning": "files/01_1820_meaning.mp3",
      "audioExample": "files/01_1820_example.mp3",
      "textMeaning": "To <i>validate</i> is to make someone feel that his or her ideas and feelings are respected.",
      "textExample": "Winning first prize will <b>validate</b> all of Tony’s hard work.",
      "transcription": "[vǽlədèit]",
      "textExampleTranslate": "Получение первого приза подтвердит всю тяжелую работу Тони",
      "textMeaningTranslate": "Подтвердить - значит заставить кого-то почувствовать, что его или ее идеи и чувства уважают",
      "wordTranslate": "проверка",
      "wordsPerExampleSentence": 10
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb8",
      "group": 3,
      "page": 0,
      "word": "survey",
      "image": "files/01_1817.jpg",
      "audio": "files/01_1817.mp3",
      "audioMeaning": "files/01_1817_meaning.mp3",
      "audioExample": "files/01_1817_example.mp3",
      "textMeaning": "A <i>survey</i> is a set of questions that are asked to a large number of people in order to find out about opinions.",
      "textExample": "I filled out a <b>survey</b> about my shopping experience at the department store.",
      "transcription": "[sərvéi]",
      "textExampleTranslate": "Я заполнил опрос о моем опыте покупок в универмаге",
      "textMeaningTranslate": "Опрос - это набор вопросов, которые задают большому количеству людей, чтобы узнать о мнениях",
      "wordTranslate": "опрос",
      "wordsPerExampleSentence": 13
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbb9",
      "group": 3,
      "page": 0,
      "word": "target",
      "image": "files/01_1818.jpg",
      "audio": "files/01_1818.mp3",
      "audioMeaning": "files/01_1818_meaning.mp3",
      "audioExample": "files/01_1818_example.mp3",
      "textMeaning": "To <i>target</i> is to aim an attack at someone or something.",
      "textExample": "Scientists are looking for new drugs to <b>target</b> cancer cells.",
      "transcription": "[tάːrgit]",
      "textExampleTranslate": "Ученые ищут новые лекарства для нацеливания на раковые клетки",
      "textMeaningTranslate": "Таргетировать это нацеливать нападение на кого-то или что-то",
      "wordTranslate": "мишень",
      "wordsPerExampleSentence": 10
    },
    {
      "id": "5e9f5ee35eb9e72bc21afbbb",
      "group": 3,
      "page": 0,
      "word": "trend",
      "image": "files/01_1819.jpg",
      "audio": "files/01_1819.mp3",
      "audioMeaning": "files/01_1819_meaning.mp3",
      "audioExample": "files/01_1819_example.mp3",
      "textMeaning": "A <i>trend</i> is a general tendency in the way a situation is changing or developing.",
      "textExample": "Lucy likes to think she started this fashion <b>trend</b>.",
      "transcription": "[trend]",
      "textExampleTranslate": "Люси нравится думать, что она начала эту модную тенденцию",
      "textMeaningTranslate": "Тенденция - это общая тенденция изменения или развития ситуации",
      "wordTranslate": "тренд",
      "wordsPerExampleSentence": 9
    }
  ],
};

export default function MockWordsApi(difficulty) {
  return wordData[difficulty];
}
