const IN_PROGRESS_SPRINT_GAME = 'in-progress';
const FINISHED_SPRINT_GAME = 'finished';
const EVENT_NAME_SPRINT_GAME = 'status';

export { IN_PROGRESS_SPRINT_GAME, FINISHED_SPRINT_GAME, EVENT_NAME_SPRINT_GAME };
